name: Build
on:
  push:
  schedule:
    - cron: '0 5 * * MON'  # At 05:00 UTC on Monday

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example_device:
          - examples/knx.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ESPHome
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install esphome
      - name: Compile ESPHome firmware
        run: |
          . .venv/bin/activate
          esphome compile ${{ matrix.example_device }}
